<template>
  <div class="">
    <div class="inlineTnfo_title">
      <p>苏州银行昆山分行积极开展“同在蓝天下--慈善一日捐”爱心捐助活动</p>
      <p>2017.07.12 10:00</p>
    </div>
    <div class="inlineTnfo_content">
      <p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>
      <p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>
      <p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>
      <p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>
      <p>大家好大家好大家好大家好大家好大家好大家好大家好</p>
      <p>大家好大家好大家好大家好大家好大家好大家好大家好</p>
    </div>
  </div>
</template>

<script type="text/ecmascript-6">
  export default {
    data () {
      return {
      }
    },
    methods: {
    },
    created: function () {
      document.title = '行内信息'
    }
  }
</script>

<style lang="less" rel="stylesheet/less">
  .inlineTnfo_title{
    width:100%;
    padding:10px;
    box-sizing:border-box;
    background:white;
    border-bottom:1px solid #e9e9e9;
  }
  .inlineTnfo_title>p:first-child{
    font-size:18px;
    line-height:150%;
    margin-bottom:10px;
  }
  .inlineTnfo_title>p:last-child{
    font-size:12px;
    color:#666666;
  }
  .inlineTnfo_content{
    padding:10px;
    width:100%;
    box-sizing:border-box;
  }
  .inlineTnfo_content>p{
    line-height:150%;
    font-size:14px;
    color:#5a5a5a;
  }
</style>
